name: Publish NuGet Package

on:
  push:
    tags:
      - 'release/*/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/SimpleMapper.sln

      - name: Build project
        run: dotnet build ./src/SimpleMapper.sln --configuration Release

      - name: Extract version from tag
        id: extract_version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION=$(echo "$TAG" | awk -F/ '{print $3}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Pack NuGet package
        run: dotnet pack ./src/SimpleMapper.sln --configuration Release --output ./nupkgs /p:PackageVersion=${{ steps.extract_version.outputs.version }}

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_SECRET }} --no-symbols true
        
      - name: Push to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_GITHUB_TOKEN }}
        run: |
          dotnet nuget add source \
            --username ${{ github.repository_owner }} \
            --password $GITHUB_TOKEN \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push ./nupkgs/*.nupkg \
            --source github \
            --skip-duplicate
