name: Publish NuGet Package

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/SimpleMapper.sln

      - name: Build project
        run: dotnet build ./src/SimpleMapper.sln --configuration Release

      - name: Pack NuGet package
        run: dotnet pack ./src/SimpleMapper.sln --configuration Release --output ./nupkgs 

      - name: Publish Nuget packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key  ${{ secrets.NUGET_SECRET }} --no-symbols true
        
